#!/bin/sh
# PreToolUse guard: ~/.claude/settings.json is generated by install.sh's jq
# merge of claude-global/settings.json (base) + ~/.claude/settings.local.json
# (overlay). Direct edits get clobbered on the next install/post-merge run, so
# block the tool call and direct the agent to the right source file.
#
# Wired up via the PreToolUse Edit|Write|MultiEdit matcher in
# claude-global/settings.json. Reads the tool input as JSON on stdin and
# extracts the file_path field.

input=$(cat)
file_path=$(printf '%s' "$input" | jq -r '.tool_input.file_path // empty' 2>/dev/null)

target="$HOME/.claude/settings.json"

case "$file_path" in
  "$target"|"~/.claude/settings.json")
    cat >&2 <<EOF
BLOCKED: $target is a generated file (jq-merged from base + overlay) and will
be overwritten on the next install.sh / post-merge run. Edit the source instead:

  - $HOME/.dotfiles/claude-global/settings.json   (committed base, shared across machines)
  - $HOME/.claude/settings.local.json             (machine-local overlay)

Then re-run \$HOME/.dotfiles/install.sh (or hooks/post-merge) to regenerate.
EOF
    exit 2
    ;;
esac
exit 0
